import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

type Time = {
  datetime: number;
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] px-4">
        <header className="flex justify-between items-center text-lg font-bold leading-[3rem]">
          <Link href={'/'}>Country App 🌎 </Link>
        </header>
        <main className='"py-8 m-10 text-center'>{children}</main>
        <footer className="text-center leading-[3rem] opacity-70">
          © {new Date().getFullYear()}{' '}
          <a href="https://github.com/pabrig">By Pablo Rigalli</a>.
        </footer>
      </body>
    </html>
  );
}
